apiVersion: v1
kind: Namespace
metadata:
  name: "event-router"
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventrouter 
  namespace: event-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventrouter 
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventrouter 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventrouter
subjects:
- kind: ServiceAccount
  name: eventrouter
  namespace: event-router